users = User.create!(user_name: "charcoal", email: "charlett@example.com", about_me: "i do things", password: "password", phone_number: "888-888-8888", profile_pic: "../bold_angel_frontend/assets/image/bg_5.jpg")

photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_1.jpg", carousel: 1)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_2.jpg", carousel: 1)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_3.jpg", carousel: 1)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_4.jpg", carousel: 1)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_6.jpg", carousel: 1)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_1.jpg", carousel: 2)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_2.jpg", carousel: 2)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_3.jpg", carousel: 2)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_4.jpg", carousel: 2)
photo_ones = PhotoOne.create!(image: "../bold_angel_frontend/assets/image/bg_6.jpg", carousel: 2)
